baseURL = 'https://yeganemehr.net/'
languageCode = 'en-us'
title = 'Amir H. Yeganemehr'
theme = 'hugo-coder'
enableGitInfo = true
enableRobotsTXT = true


[params]
  author = "Amir H. Yeganemehr"
  info = "From Design to Deployment"
  description = "Yeganemehr's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "/me.jpg"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2024

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  commit = "https://github.com/yeganemehr/yeganemehr.net/tree"

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/yeganemehr/"
[[params.social]]
  name = "Linkedin"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 2
  url = "https://www.linkedin.com/in/yeganemehr/"
[[params.social]]
  name = "Email"
  icon = "fa fa-envelope fa-2x"
  weight = 3
  url = "mailto:ygnmehr@gmail.com"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"